# -*- coding: utf-8 -*-
"""Untitled44.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W2wI4YuGps3Mw_8akspMHKtw0ChxS8_h

# 1️. Import Required Libraries
"""

# =========================================================
# 1. IMPORT REQUIRED LIBRARIES
# =========================================================

import pandas as pd
import numpy as np

# Visualization
import matplotlib.pyplot as plt
import seaborn as sns

# Preprocessing
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

# Model selection
from sklearn.model_selection import train_test_split, StratifiedKFold, cross_val_score

# Machine Learning Models
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier

# Evaluation Metrics
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    roc_curve,
    confusion_matrix,
    classification_report
)

# Model saving
import joblib

print("Libraries imported successfully.")

"""# 2. Upload Datasets"""

# =========================================================
# 2. UPLOAD DATASETS
# =========================================================

from google.colab import files

uploaded = files.upload()

print("Datasets uploaded successfully.")

"""# 3. Load Dataset 1 – WDBC"""

# =========================================================
# 3. LOAD DATASET 1 (WDBC DATASET)
# Wisconsin Diagnostic Breast Cancer
# =========================================================

columns = [
"id","diagnosis",
"radius_mean","texture_mean","perimeter_mean","area_mean","smoothness_mean",
"compactness_mean","concavity_mean","concave_points_mean","symmetry_mean","fractal_dimension_mean",
"radius_se","texture_se","perimeter_se","area_se","smoothness_se",
"compactness_se","concavity_se","concave_points_se","symmetry_se","fractal_dimension_se",
"radius_worst","texture_worst","perimeter_worst","area_worst","smoothness_worst",
"compactness_worst","concavity_worst","concave_points_worst","symmetry_worst","fractal_dimension_worst"
]

df1 = pd.read_csv("wdbc.data", names=columns)

df1.head()

"""# 4.Basic Dataset Information"""

# =========================================================
# 4. DATASET INFORMATION
# =========================================================

print("Dataset Shape:", df1.shape)

df1.info()

df1.describe()

"""# 5. Missing Values Heatmap (Before Preprocessing)"""

# =========================================================
# 5. MISSING VALUES HEATMAP (BEFORE PREPROCESSING)
# =========================================================

plt.figure(figsize=(10,6))

sns.heatmap(df1.isnull(), cbar=False)

plt.title("Missing Values Heatmap - Before Preprocessing")

plt.show()

"""The Wisconsin Diagnostic Breast Cancer (WDBC) dataset is already clean

# 6. Class distribution
"""

# =========================================================
# 6. CLASS DISTRIBUTION
# =========================================================

plt.figure(figsize=(5,4))

sns.countplot(x=df1["diagnosis"])

plt.title("Class Distribution")

plt.show()

"""# 7. Correlation Heatmap"""

# =========================================================
# 7. CORRELATION HEATMAP
# =========================================================

plt.figure(figsize=(12,10))

sns.heatmap(df1.drop("diagnosis", axis=1).corr(), cmap="coolwarm")

plt.title("Feature Correlation Heatmap")

plt.show()

"""# 8. Feature Distribution"""

# =========================================================
# 8. FEATURE DISTRIBUTION
# =========================================================

df1.hist(figsize=(18,12))

plt.suptitle("Feature Distributions")

plt.show()

"""# 9. Boxplot for Outlier Detection"""

# =========================================================
# 9. OUTLIER DETECTION
# =========================================================

plt.figure(figsize=(18,6))

sns.boxplot(data=df1.drop(["id","diagnosis"], axis=1))

plt.xticks(rotation=90)

plt.title("Boxplots for Outlier Detection")

plt.show()

"""# 10. Preprocess Dataset 1"""

# =========================================================
# 4. PREPROCESS DATASET 1
# =========================================================

# Remove ID column
df1.drop("id", axis=1, inplace=True)

# Convert labels to numeric
df1["diagnosis"] = df1["diagnosis"].map({"M":1, "B":0})

# Features and Target
X1 = df1.drop("diagnosis", axis=1)
y1 = df1["diagnosis"]

print("Dataset 1 shape:", X1.shape)

"""# 11. Train-Test Split"""

# =========================================================
# 6. TRAIN–TEST SPLIT
# Split dataset into training and testing sets
# Stratified split maintains class distribution
# =========================================================

from sklearn.model_selection import train_test_split

X_train1, X_test1, y_train1, y_test1 = train_test_split(
    X1,
    y1,
    test_size=0.2,
    random_state=42,
    stratify=y1
)

print("Training data shape:", X_train1.shape)
print("Testing data shape:", X_test1.shape)

"""# 7. Feature Scaling"""

# =========================================================
# 7. FEATURE SCALING
# Standardization improves ML model performance
# Fit scaler ONLY on training data to avoid data leakage
# =========================================================

from sklearn.preprocessing import StandardScaler

scaler1 = StandardScaler()

X_train1_scaled = scaler1.fit_transform(X_train1)

X_test1_scaled = scaler1.transform(X_test1)

print("Feature scaling completed.")

"""# 13.  Missing Heatmap After Preprocessing"""

# =========================================================
# 13. MISSING HEATMAP AFTER PREPROCESSING
# =========================================================

plt.figure(figsize=(10,6))

sns.heatmap(pd.DataFrame(X_train1_scaled).isnull(), cbar=False)

plt.title("Missing Values After Preprocessing")

plt.show()

"""# 14. Define PCA Component Cases"""

# =========================================================
# 14. PCA COMPONENT CASES
# Compare different dimensionality reductions
# =========================================================

pca_cases = {

"No PCA (30)": None,

"PCA 15": 15,

"PCA 10": 10,

"PCA 5": 5

}

print("PCA experiment cases created.")

"""# 15️. PCA Explained Variance Plot"""

# =========================================================
# 15. PCA EXPLAINED VARIANCE
# =========================================================

pca = PCA()

pca.fit(X_train1_scaled)

explained_variance = np.cumsum(pca.explained_variance_ratio_)

plt.figure(figsize=(6,4))

plt.plot(explained_variance, marker='o')

plt.xlabel("Number of Principal Components")

plt.ylabel("Cumulative Explained Variance")

plt.title("PCA Explained Variance")

plt.grid(True)

plt.show()

"""# 16️. Define Machine Learning Models"""

# =========================================================
# 16. DEFINE MACHINE LEARNING MODELS
# =========================================================

models = {

    "Logistic Regression": LogisticRegression(max_iter=1000),

    "SVM": SVC(kernel="rbf", probability=True),

    "Random Forest": RandomForestClassifier(n_estimators=100),

    "KNN": KNeighborsClassifier(n_neighbors=5)

}

print("Models defined successfully")

"""# 17️. Cross Validation Setup"""

# =========================================================
# 17. CROSS VALIDATION SETUP
# =========================================================

from sklearn.model_selection import StratifiedKFold

# StratifiedKFold keeps class distribution balanced in each fold
cv = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)

print("Cross validation strategy created")

"""# 18️. Hyperparameter Tuning Grids"""

# =========================================================
# 18. HYPERPARAMETER TUNING GRIDS
# =========================================================

param_grids = {

    "SVM": {
        "C": [0.1, 1, 10],
        "gamma": ["scale", "auto"],
        "kernel": ["rbf"]
    },

    "Random Forest": {
        "n_estimators": [100, 200],
        "max_depth": [None, 10, 20]
    },

    "KNN": {
        "n_neighbors": [3, 5, 7]
    }

}

print("Hyperparameter grids defined successfully")

"""# 19. Run Experiments for Each PCA Case"""

# =========================================================
# 19. RUN EXPERIMENTS FOR EACH PCA CASE (FIXED VERSION)
# =========================================================

from sklearn.model_selection import GridSearchCV

results = []
best_models_store = {}

for case_name, n_components in pca_cases.items():

    print("\nRunning experiment:", case_name)

    # Apply PCA if required
    if n_components is None:
        X_train_case = X_train1_scaled
        X_test_case = X_test1_scaled
    else:
        pca = PCA(n_components=n_components)

        X_train_case = pca.fit_transform(X_train1_scaled)
        X_test_case = pca.transform(X_test1_scaled)

    # Train models
    for model_name, model in models.items():

        # Hyperparameter tuning
        if model_name in param_grids:

            grid = GridSearchCV(
                estimator=model,
                param_grid=param_grids[model_name],
                cv=cv,                 # FIXED (use StratifiedKFold)
                n_jobs=-1
            )

            grid.fit(X_train_case, y_train1)

            best_model = grid.best_estimator_
            best_params = grid.best_params_

        else:
            best_model = model
            best_model.fit(X_train_case, y_train1)
            best_params = "Default"

        # Store best trained model
        best_models_store[(case_name, model_name)] = best_model

        # Predictions
        y_train_pred = best_model.predict(X_train_case)
        y_test_pred = best_model.predict(X_test_case)

        # Accuracy
        train_acc = accuracy_score(y_train1, y_train_pred)
        test_acc = accuracy_score(y_test1, y_test_pred)

        # Cross validation
        cv_scores = cross_val_score(best_model, X_train_case, y_train1, cv=cv)
        cv_mean = cv_scores.mean()

        # Metrics
        precision = precision_score(y_test1, y_test_pred)
        recall = recall_score(y_test1, y_test_pred)
        f1 = f1_score(y_test1, y_test_pred)

        # Overfitting gap
        gap = train_acc - test_acc

        # Save results
        results.append([
            case_name,
            model_name,
            best_params,
            train_acc,
            test_acc,
            cv_mean,
            gap,
            precision,
            recall,
            f1
        ])

"""# 11. Create Proper Results Table"""

# =========================================================
# 20. CREATE RESULTS TABLE
# =========================================================

results_df = pd.DataFrame(

    results,

    columns=[
        "PCA Case",
        "Model",
        "Best Parameters",
        "Train Accuracy",
        "Test Accuracy",
        "CV Score",
        "Overfitting Gap",
        "Precision",
        "Recall",
        "F1 Score"
    ]

)

# Round values for better readability
results_df = results_df.round(4)

results_df

"""# 21. Sorting Best Model (Multi-Metric Evaluation)"""

# =========================================================
# 21. SELECT BEST MODEL BASED ON MULTIPLE METRICS
# =========================================================

# Create a combined evaluation score
results_df["Final Score"] = (

    results_df["F1 Score"] * 0.4 +       # Most important
    results_df["Recall"] * 0.3 +         # Important for medical detection
    results_df["CV Score"] * 0.2 +       # Model stability
    (1 - results_df["Overfitting Gap"]) * 0.1   # Penalize overfitting

)

# Sort models by best score
best_models = results_df.sort_values(
    by="Final Score",
    ascending=False
)

# Display ranked models
best_models

"""# 22. Identify the Best Model Configuration"""

# =========================================================
# 22. IDENTIFY BEST MODEL CONFIGURATION
# =========================================================

# Get the top row from the ranked models
best_row = best_models.iloc[0]

print("Best Model Configuration:")
print(best_row)

# Extract important information
best_pca_case = best_row["PCA Case"]
best_model_name = best_row["Model"]
best_params = best_row["Best Parameters"]

print("\nBest PCA Case:", best_pca_case)
print("Best Model:", best_model_name)
print("Best Hyperparameters:", best_params)

"""# 14.Retrain Best Model on Selected Configuration"""

# =========================================================
# 23. RETRAIN BEST MODEL USING BEST CONFIGURATION
# =========================================================

best_model = best_models_store[(best_pca_case, best_model_name)]

if best_pca_case == "No PCA (30)":

    X_train_best = X_train1_scaled
    X_test_best = X_test1_scaled

else:

    n_comp = int(best_pca_case.split()[1])

    pca = PCA(n_components=n_comp)

    X_train_best = pca.fit_transform(X_train1_scaled)
    X_test_best = pca.transform(X_test1_scaled)

best_model.fit(X_train_best, y_train1)

y_pred = best_model.predict(X_test_best)

print("Best model retrained successfully.")

"""# 15. Confusion Matrix and Detailed Classification Report"""

# =========================================================
# 24. CONFUSION MATRIX
# =========================================================

from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test1, y_pred)

plt.figure(figsize=(5,4))

sns.heatmap(
    cm,
    annot=True,
    fmt="d",
    cmap="Blues",
    xticklabels=["Benign","Malignant"],
    yticklabels=["Benign","Malignant"]
)

plt.xlabel("Predicted Label")
plt.ylabel("True Label")

plt.title("Confusion Matrix - Best Model")

plt.show()

"""# 25️⃣ Classification Report"""

# =========================================================
# 25. CLASSIFICATION REPORT
# =========================================================

from sklearn.metrics import classification_report

print("Classification Report:\n")

print(classification_report(y_test1, y_pred))

"""# 16. ROC Curve and AUC Score of best model"""

# =========================================================
# 26. ROC CURVE
# =========================================================

from sklearn.metrics import roc_curve, roc_auc_score

# Get probability scores
y_prob = best_model.predict_proba(X_test_best)[:,1]

# ROC values
fpr, tpr, thresholds = roc_curve(y_test1, y_prob)

# AUC score
auc_score = roc_auc_score(y_test1, y_prob)

print("AUC Score:", auc_score)

plt.figure(figsize=(6,5))

plt.plot(
    fpr,
    tpr,
    label="ROC Curve (AUC = %.3f)" % auc_score
)

plt.plot([0,1],[0,1],'--')

plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")

plt.title("ROC Curve - Best Model")

plt.legend()

plt.show()

"""27️⃣ Learning Curve"""

# =========================================================
# 27. LEARNING CURVE
# =========================================================

from sklearn.model_selection import learning_curve

train_sizes, train_scores, val_scores = learning_curve(

    best_model,
    X_train_best,
    y_train1,
    cv=5,
    n_jobs=-1

)

train_mean = train_scores.mean(axis=1)
val_mean = val_scores.mean(axis=1)

plt.figure(figsize=(6,5))

plt.plot(train_sizes, train_mean, label="Training Score")
plt.plot(train_sizes, val_mean, label="Validation Score")

plt.xlabel("Training Size")
plt.ylabel("Accuracy")

plt.title("Learning Curve")

plt.legend()

plt.show()

"""# 17. Final Experiment Summary"""

# =========================================================
# 29. FINAL MODEL SUMMARY
# =========================================================

print("========== FINAL MODEL SUMMARY ==========")

print("\nBest Dataset: WDBC Breast Cancer Dataset")
print("Best PCA Configuration:", best_pca_case)
print("Best Model:", best_model_name)

print("\nPerformance Metrics:")

print("Train Accuracy:", round(best_row["Train Accuracy"],4))
print("Test Accuracy:", round(best_row["Test Accuracy"],4))
print("Cross Validation Score:", round(best_row["CV Score"],4))
print("Overfitting Gap:", round(best_row["Overfitting Gap"],4))
print("Precision:", round(best_row["Precision"],4))
print("Recall:", round(best_row["Recall"],4))
print("F1 Score:", round(best_row["F1 Score"],4))
print("Final Score:", round(best_row["Final Score"],4))

print("\n=========================================")

"""# 19. Load Dataset 2 (Original Wisconsin Breast Cancer)"""

# =========================================================
# 30. LOAD DATASET 2
# Original Wisconsin Breast Cancer Dataset
# =========================================================

columns2 = [
"id",
"clump_thickness",
"uniformity_cell_size",
"uniformity_cell_shape",
"marginal_adhesion",
"single_epithelial_cell_size",
"bare_nuclei",
"bland_chromatin",
"normal_nucleoli",
"mitoses",
"class"
]

df2 = pd.read_csv("breast-cancer-wisconsin.data", names=columns2)

df2.head()

"""# 31️⃣ Basic Dataset Information"""

# =========================================================
# 31. DATASET 2 INFORMATION
# =========================================================

print("Dataset Shape:", df2.shape)

df2.info()

df2.describe()

"""# 32️⃣ Missing Values Heatmap (Before Preprocessing)"""

# =========================================================
# 32. MISSING VALUES HEATMAP (BEFORE PREPROCESSING)
# =========================================================
df2.replace("?", np.nan, inplace=True)

print("Converted '?' to NaN")
plt.figure(figsize=(10,6))

sns.heatmap(df2.isnull(), cbar=False)

plt.title("Missing Values Heatmap - Dataset 2 (Before Preprocessing)")

plt.show()

"""# Step 34 – Preprocessing (Handle Missing Values)"""

# =========================================================
# 34. HANDLE MISSING VALUES
# =========================================================

# Convert column to numeric
df2["bare_nuclei"] = df2["bare_nuclei"].astype(float)

# Fill missing values with mean
df2.fillna(df2.mean(), inplace=True)

print("Missing values handled successfully")

"""# Step 35 – Missing Heatmap After Preprocessing"""

# =========================================================
# 35. MISSING VALUES HEATMAP (AFTER PREPROCESSING)
# =========================================================

plt.figure(figsize=(10,6))

sns.heatmap(df2.isnull(), cbar=False)

plt.title("Missing Values Heatmap - Dataset 2 (After Preprocessing)")

plt.show()

"""# 33️⃣ Class Distribution"""

# =========================================================
# 33. CLASS DISTRIBUTION
# =========================================================

plt.figure(figsize=(5,4))

sns.countplot(x=df2["class"])

plt.title("Class Distribution - Dataset 2")

plt.show()

"""# 37️⃣ Correlation Heatmap"""

# =========================================================
# 37. CORRELATION HEATMAP
# =========================================================

plt.figure(figsize=(8,6))

sns.heatmap(df2.corr(), cmap="coolwarm")

plt.title("Feature Correlation Heatmap - Dataset 2")

plt.show()

"""# 38️⃣ Feature Distribution (Dataset-2)"""

# =========================================================
# 38. FEATURE DISTRIBUTION
# =========================================================

df2.drop("class", axis=1).hist(figsize=(12,8))

plt.suptitle("Feature Distributions - Dataset 2")

plt.show()

"""# 34️⃣ Convert Target Variabl"""

# =========================================================
# 38. CONVERT TARGET VARIABLE
# =========================================================

df2.drop("id", axis=1, inplace=True)

df2["class"] = df2["class"].map({2:0, 4:1})

X2 = df2.drop("class", axis=1)
y2 = df2["class"]

print("Feature shape:", X2.shape)

"""# 39️⃣ Train-Test Split"""

# =========================================================
# 39. TRAIN TEST SPLIT
# =========================================================

X_train2, X_test2, y_train2, y_test2 = train_test_split(
    X2,
    y2,
    test_size=0.2,
    random_state=42,
    stratify=y2
)

print("Training shape:", X_train2.shape)
print("Testing shape:", X_test2.shape)

"""# 23.Feature Scaling"""

# =========================================================
# 40. FEATURE SCALING
# =========================================================

scaler2 = StandardScaler()

X_train2_scaled = scaler2.fit_transform(X_train2)

X_test2_scaled = scaler2.transform(X_test2)

print("Scaling completed")

"""# 41️⃣ PCA Explained Variance"""

# =========================================================
# 41. PCA EXPLAINED VARIANCE
# =========================================================

pca2 = PCA()

pca2.fit(X_train2_scaled)

explained_variance2 = np.cumsum(pca2.explained_variance_ratio_)

plt.figure(figsize=(6,4))

plt.plot(explained_variance2, marker="o")

plt.xlabel("Number of Components")
plt.ylabel("Cumulative Explained Variance")

plt.title("PCA Explained Variance - Dataset 2")

plt.grid(True)

plt.show()

"""# 42️⃣ PCA Experiment Cases"""

# =========================================================
# 42. PCA CASES
# =========================================================

pca_cases_2 = {

"No PCA (9)": None,
"PCA 5": 5,
"PCA 3": 3,
"PCA 2": 2

}

print("PCA configurations created")

"""# 25.Run Experiments for Dataset 2"""

# =========================================================
# 43. RUN EXPERIMENTS FOR DATASET 2 (FIXED VERSION)
# =========================================================

from sklearn.model_selection import GridSearchCV

results_2 = []
best_models_store_2 = {}

for case_name, n_components in pca_cases_2.items():

    print("\nRunning experiment:", case_name)

    # Apply PCA if needed
    if n_components is None:
        X_train_case = X_train2_scaled
        X_test_case = X_test2_scaled

    else:
        pca = PCA(n_components=n_components)

        X_train_case = pca.fit_transform(X_train2_scaled)
        X_test_case = pca.transform(X_test2_scaled)

    for model_name, model in models.items():

        # Hyperparameter tuning
        if model_name in param_grids:

            grid = GridSearchCV(
                estimator=model,
                param_grid=param_grids[model_name],
                cv=cv,              # FIXED
                n_jobs=-1
            )

            grid.fit(X_train_case, y_train2)

            best_model = grid.best_estimator_
            best_params = grid.best_params_

        else:

            best_model = model
            best_model.fit(X_train_case, y_train2)

            best_params = "Default"

        # Store best trained model
        best_models_store_2[(case_name, model_name)] = best_model

        # Predictions
        y_train_pred = best_model.predict(X_train_case)
        y_test_pred = best_model.predict(X_test_case)

        # Accuracy
        train_acc = accuracy_score(y_train2, y_train_pred)
        test_acc = accuracy_score(y_test2, y_test_pred)

        # Cross validation
        cv_scores = cross_val_score(best_model, X_train_case, y_train2, cv=cv)
        cv_mean = cv_scores.mean()

        # Metrics
        precision = precision_score(y_test2, y_test_pred)
        recall = recall_score(y_test2, y_test_pred)
        f1 = f1_score(y_test2, y_test_pred)

        # Overfitting gap
        gap = train_acc - test_acc

        results_2.append([
            case_name,
            model_name,
            best_params,
            train_acc,
            test_acc,
            cv_mean,
            gap,
            precision,
            recall,
            f1
        ])

"""# 26. Create Results Table for Dataset 2"""

# =========================================================
# 44. RESULTS TABLE (DATASET 2)
# =========================================================

results_df2 = pd.DataFrame(

    results_2,

    columns=[
        "PCA Case",
        "Model",
        "Best Params",
        "Train Accuracy",
        "Test Accuracy",
        "CV Score",
        "Overfitting Gap",
        "Precision",
        "Recall",
        "F1 Score"
    ]

)

results_df2 = results_df2.round(4)

results_df2

"""# 27. Select Best Model (Dataset 2)"""

# =========================================================
# 45. SELECT BEST MODEL (DATASET 2)
# =========================================================

results_df2["Final Score"] = (

    results_df2["F1 Score"] * 0.4 +
    results_df2["Recall"] * 0.3 +
    results_df2["CV Score"] * 0.2 +
    (1 - results_df2["Overfitting Gap"]) * 0.1

)

best_models_2 = results_df2.sort_values(
    by="Final Score",
    ascending=False
)

best_models_2

# =========================================================
# 46. IDENTIFY BEST MODEL CONFIGURATION
# =========================================================

best_row2 = best_models_2.iloc[0]

print("Best Model Configuration (Dataset 2):")
print(best_row2)

best_pca_case2 = best_row2["PCA Case"]
best_model_name2 = best_row2["Model"]
best_params2 = best_row2["Best Params"]

print("\nBest PCA Case:", best_pca_case2)
print("Best Model:", best_model_name2)
print("Best Hyperparameters:", best_params2)

"""# 28. Retrain Best Model"""

# =========================================================
# 47. RETRAIN BEST MODEL (DATASET 2) - FIXED
# =========================================================

best_model2 = best_models_store_2[(best_pca_case2, best_model_name2)]

if best_pca_case2 == "No PCA (9)":

    X_train_best2 = X_train2_scaled
    X_test_best2 = X_test2_scaled

else:

    n_comp = int(best_pca_case2.split()[1])

    pca = PCA(n_components=n_comp)

    X_train_best2 = pca.fit_transform(X_train2_scaled)
    X_test_best2 = pca.transform(X_test2_scaled)

best_model2.fit(X_train_best2, y_train2)

y_pred2 = best_model2.predict(X_test_best2)

print("Best model retrained successfully.")

"""# 29.Confusion Matrix (Dataset 2)"""

# =========================================================
# 48. CONFUSION MATRIX
# =========================================================

cm2 = confusion_matrix(y_test2, y_pred2)

plt.figure(figsize=(5,4))

sns.heatmap(
    cm2,
    annot=True,
    fmt="d",
    cmap="Greens",
    xticklabels=["Benign","Malignant"],
    yticklabels=["Benign","Malignant"]
)

plt.xlabel("Predicted")
plt.ylabel("Actual")

plt.title("Confusion Matrix - Dataset 2")

plt.show()

"""# 30. ROC Curve (Dataset 2)"""

# =========================================================
# 49. ROC CURVE
# =========================================================

y_prob2 = best_model2.predict_proba(X_test_best2)[:,1]

fpr2, tpr2, _ = roc_curve(y_test2, y_prob2)

auc2 = roc_auc_score(y_test2, y_prob2)

plt.figure(figsize=(6,5))

plt.plot(fpr2, tpr2, label="AUC = %.3f" % auc2)

plt.plot([0,1],[0,1],'--')

plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")

plt.title("ROC Curve - Dataset 2")

plt.legend()

plt.show()

# =========================================================
# LEARNING CURVE - DATASET 2
# =========================================================

from sklearn.model_selection import learning_curve

train_sizes, train_scores, val_scores = learning_curve(

    best_model2,
    X_train_best2,
    y_train2,
    cv=5,
    n_jobs=-1

)

train_mean = train_scores.mean(axis=1)
val_mean = val_scores.mean(axis=1)

plt.figure(figsize=(6,5))

plt.plot(train_sizes, train_mean, label="Training Score")
plt.plot(train_sizes, val_mean, label="Validation Score")

plt.xlabel("Training Size")
plt.ylabel("Accuracy")

plt.title("Learning Curve - Dataset 2")

plt.legend()

plt.show()

"""# 31. Compare Dataset 1 and Dataset 2"""

# =========================================================
# 50. DATASET COMPARISON
# =========================================================

comparison_df = pd.DataFrame({

"Dataset": ["Dataset 1 (WDBC)", "Dataset 2 (Original)"],

"Best Model": [
    best_model_name,
    best_model_name2
],

"Test Accuracy": [
    best_row["Test Accuracy"],
    best_row2["Test Accuracy"]
],

"F1 Score": [
    best_row["F1 Score"],
    best_row2["F1 Score"]
]

})

comparison_df

"""# 32. Comparison Visualization"""

plt.figure(figsize=(6,4))

sns.barplot(
    data=comparison_df,
    x="Dataset",
    y="Test Accuracy"
)

plt.title("Best Model Accuracy Comparison")

plt.show()